### ISSUE TITLE
java.lang.NullPointerException in com.dragome.compiler.units.ClassUnit.removeSubUnit()

### ISSUE THREAD

**Issue by purplezimmermann** [purplezimmermann/dragome-sdk#13]
When called on `instanceof NullClassUnit`

```
Exception in thread "Thread-19" java.lang.RuntimeException: java.lang.NullPointerException
	at com.dragome.compiler.DragomeJsCompiler.compile(DragomeJsCompiler.java:175)
	at com.dragome.web.helpers.serverside.DragomeCompilerLauncher.compileWithMainClass(DragomeCompilerLauncher.java:74)
	at com.dragome.web.serverside.compile.watchers.DirectoryWatcher.compile(DirectoryWatcher.java:263)
	at com.dragome.web.serverside.compile.watchers.DirectoryWatcher.startWatching(DirectoryWatcher.java:249)
	at com.dragome.web.serverside.servlets.CompilerServlet$1.run(CompilerServlet.java:106)
Caused by: java.lang.NullPointerException
	at com.dragome.compiler.units.ClassUnit.removeSubUnit(ClassUnit.java:183)
	at com.dragome.compiler.units.ClassUnit.setSuperUnit(ClassUnit.java:242)
	at com.dragome.compiler.units.ClassUnit.clear(ClassUnit.java:135)
	at com.dragome.compiler.type.TypeResolver.visit(TypeResolver.java:41)
	at com.dragome.compiler.Project.visitSuperTypes(Project.java:297)
	at com.dragome.compiler.Project.resolve(Project.java:486)
	at com.dragome.compiler.writer.Assembly.resolveNoTainting(Assembly.java:340)
	at com.dragome.compiler.DragomeJsCompiler.execute(DragomeJsCompiler.java:268)
	at com.dragome.compiler.DragomeJsCompiler.compile(DragomeJsCompiler.java:170)
	... 4 more
```

**Comment by purplezimmermann** [comment]
Solved by #15
